site_name: "Network Wrangler"
site_url: https://wsp-sag.github.io/network_wrangler
repo_url: https://github.com/wsp-sag/network_wrangler

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - toc.follow
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - autorefs
  - awesome-pages
  - mike
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          paths: [.]
          selection:
            new_path_syntax: true
          rendering:
            show_root_heading: true
            show_source: true
            heading_level: 3
  - search
  - macros

watch:
 - network_wrangler

extra:
  version:
    provider: mike
    default: latest

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - meta
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - smarty
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
