# base network
base_network:
  input_dir: "C:/Users/kulshresthaa/OneDrive/OneDrive - WSP O365/network_wrangler/example/stpaul"
  shape_file_name: "shape.geojson"
  link_file_name: "link.json"
  node_file_name: "node.geojson"
scenario:
  project_cards_filenames:
    - "C:/Users/kulshresthaa/OneDrive/OneDrive - WSP O365/network_wrangler/example/stpaul/project_cards/3_multiple_roadway_attribute_change.yml"
    - "C:/Users/kulshresthaa/OneDrive/OneDrive - WSP O365/network_wrangler/example/stpaul/project_cards/4_simple_managed_lane.yml"
    - "C:/Users/kulshresthaa/OneDrive/OneDrive - WSP O365/network_wrangler/example/stpaul/project_cards/7_simple_transit_attribute_change.yml"
  card_directory:
  glob_search:
  tags:
  write_out: True
  output_dir: "C:/Users/kulshresthaa/OneDrive/OneDrive - WSP O365/network_wrangler/scratch"
  out_prefix: "test_scen"
